services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.build
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: native-start-web:latest
    container_name: native-start-web
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/:/app/apps/web
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile.build
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: native-start-docs:latest
    container_name: native-start-docs
    expose:
      - 3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/docs/:/app/apps/docs
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.build
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: native-start-api:latest
    container_name: native-start-api
    expose:
      - 3002
    ports:
      - "3002:3002"
    volumes:
      - ./apps/api/:/app/apps/api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
