# services:
#   - type: web
#     env: node
#     name: native-start
#     repo: https://github.com/adityadeshlahre/native-start.git
#     buildFilter:
#       paths:
#         - apps/backend/**
#     buildCommand: pnpm && pnpm build --filter=web
#     startCommand: cd apps/web; pnpm start
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: fh-prod-db1
#           property: connectionString
#       - key: REDIS_URL
#         fromService:
#           name: fh-prod-redis1
#           type: redis
#           property: connectionString

#   - type: web
#     env: node
#     name: native-docs
#     repo: https://github.com/adityadeshlahre/native-start.git
#     buildFilter:
#       paths:
#         - apps/docs/**
#     buildCommand: pnpm && pnpm build --filter=docs
#     staticPublishPath: ./apps/frontend/build
#     routes:
#       - type: rewrite
#         source: /*
#         destination: /index.html
#     envVars:
#       - key: REACT_APP_GRAPHQL_HOST
#         fromService:
#           name: fh-prod-backend1
#           type: web
#           property: host

#   - type: web
#     env: node
#     name: native-api
#     repo: https://github.com/adityadeshlahre/native-start.git
#     buildFilter:
#       paths:
#         - apps/api/**
#     buildCommand: pnpm && pnpm build --filter=api
#     staticPublishPath: ./apps/frontend/build
#     routes:
#       - type: rewrite
#         source: /*
#         destination: /index.html
#     envVars:
#       - key: REACT_APP_GRAPHQL_HOST
#         fromService:
#           name: fh-prod-backend1
#           type: web
#           property: host

#   - type: redis
#     name: fh-prod-redis1
#     ipAllowList: []

# databases:
#   - name: fh-prod-db1

# need a good fix
