name: Publish Docker images

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images using Docker Compose for full setup
        run: |
          docker-compose -f docker-compose.yml build

      - name: Build Docker images using Docker Compose for web & server & api
        run: |
          docker-compose -f build.docker-compose.yml build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build Dev Docker images using Docker Compose for web & server & api
        run: |
          docker-compose -f dev.docker-compose.yml build

      - name: Build Prod Docker images using Docker Compose for web & server & api
        run: |
          docker-compose -f prod.docker-compose.yml build

      - name: Push dev web service image
        run: |
          docker tag native-start-web-dev:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web-dev:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web-dev:latest

      - name: Push dev server service image
        run: |
          docker tag native-start-docs-dev:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs-dev:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs-dev:latest

      - name: Push dev api service image
        run: |
          docker tag native-start-api-dev:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api-dev:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api-dev:latest

      - name: Push prod web service image
        run: |
          docker tag native-start-web-prod:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web-prod:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web-prod:latest

      - name: Push prod server service image
        run: |
          docker tag native-start-docs-prod:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs-prod:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs-prod:latest

      - name: Push prod api service image
        run: |
          docker tag native-start-api-prod:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api-prod:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api-prod:latest

      - name: Push web service image
        run: |
          docker tag native-start-web:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-web:latest

      - name: Push server service image
        run: |
          docker tag native-start-docs:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-docs:latest

      - name: Push api service image
        run: |
          docker tag native-start-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-api:latest

      - name: Push full web-api-server image
        run: |
          docker tag native-start-full:latest ${{ secrets.DOCKERHUB_USERNAME }}/native-start-full:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/native-start-full:latest

  render_deploy:
    name: Deploy to render
    needs: [push_to_registry]
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 5 seconds before deploying Server Service
        run: sleep 5

      - name: Deploy Server Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_SERVER }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

      - name: Sleep for 5 seconds before deploying Web Service
        run: sleep 5

      - name: Deploy Web Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_WEB }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

      - name: Sleep for 5 seconds before deploying api Service
        run: sleep 5

      - name: Deploy api Service to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_API }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
